### ISSUE TITLE
Interactive input should probably not appear in the shell history

### ISSUE THREAD

**Issue by volter** [usit-gd/zabbix-cli#23]
If I create a host and fill in the details, the details later appear in the history of the shell. While you can argue that it is a feature, it's probably not what people expect.

**Comment by usit-gd** [comment]
Hei Volter

I cannot reproduce this when filling in the details after you run a command without parameters, only when running the zabbix command with all the parameters defined. 

The history will save the complete command you run in the zabbix shell and this is the expected behavior (as it happens e.g. in bash). How do you mean it should behave?

```
[zabbix-cli rafael@zabbix-ID]$ create_host rafa.test.net '' '.+' 0
[Done]: Host (rafa.test.net) with ID: 15015 created

[zabbix-cli rafael@zabbix-ID]$ show_history
........
[5]: create_host rafa.test.net '' '.+' 0
[6]: show_history

[zabbix-cli rafael@zabbix-ID]$ create_host
--------------------------------------------------------
# Hostname: rafa.test.net
# Hostgroups[All-hosts]: 
# Proxy [.+]: 
# Status [0]: 0
--------------------------------------------------------
[Done]: Host (rafa.test.net) with ID: 15016 created

[zabbix-cli rafael@zabbix-ID]$ show_history
.....
[5]: create_host rafa.test.net '' '.+' 0
[6]: show_history
[7]: remove_host 15015
[8]: create_host
[9]: show_history

```

Thanks for your report.
regards,
Rafael Martinez

**Comment by rafaelma** [comment]
No feedback. Issue closed.
