### ISSUE TITLE
Why is there and SNMP created?

### ISSUE THREAD

**Issue by garelp** [usit-gd/zabbix-cli#51]
Hi,

When I use create_host, it always add an SNMP interface in addition to the default one. How can I prevent this to happen?

And also, is there a way to add a host by name and indicate the ip address instead in the create_host function?

Thanks.

**Comment by gilcot** [comment]
😆 I came here with the same questions 😉 

I think we should be able to provide a last parameter to  say what kind of interface(s) [a case insensitive coma-separed-list in: agent/SNMP/JMX/IPMI] and use the default if not specified 

Currently, the parameters for create_host are: [hostname|IP] [hostgroups] [proxy] [status]    
Two others parameters may be added so:  [hostname|IP] [hostgroups] [proxy] [status] [display] [interface]   
Where [display] will be used as "visible name" when provided (otherwise use the first argument dns-hostname|ip-address) ; and [interface] is as previously said. 

What do you think about those suggestions? Are they difficult to implement?

**Comment by paalbra** [comment]
I agree that the SNMP interface shouldn't be added. The CLI should behave more like the web interface (creating one agent interface).

This issue is set to the next major milestone (2.0). It should be removed in that version. If you want the SNMP interface one could create it with `create_host_interface`.
