### ISSUE TITLE
Support python 3

### ISSUE THREAD

**Issue by rafaelma** [usit-gd/zabbix-cli#59]
About time to start supporting python version 3

**Comment by rafaelma** [comment]
Pull request merged with commit c8a4622011bc6be3f1d2e938b17f2b8a13ecb569

**Comment by paalbra** [comment]
Commit c8a4622 broke python2 support by adding keyword arguments to os.chmod.

"TypeError: chmod() takes no keyword arguments"

**Comment by paalbra** [comment]
_Some_ fixed added in 1dc02b9

**Comment by paalbra** [comment]
The current master branch has some different issues in both python 2 and 3. Fixes are required to make any version fully supported.

I believe that this might be the time to abandon python 2 support and go for python 3 only. Python 3 is becoming the default for linux distros and python 2 will be retired not to far into the future: https://pythonclock.org/

**Comment by paalbra** [comment]
chmod issue got fixed in e6cec615cb363499d8252ac2da42f5b48b5f4c4e

**Comment by arrfab** [comment]
@paalbra : While I understand that some people want to exclusively support python 3, the issue is that there are *plenty* of still supported OS releases (think RHEL/CentOS 6 and even 7) that still only default to python 2 (2.7 for the .el7 case), so breaking python compat would mean that it would be impossible to use zabbix-cli on such platforms (or find some other way to install python 3 in parallel, etc)

**Comment by paalbra** [comment]
As seen in #87 there are more issues with python 3. And there might still be more.

I'm going to close this issue assuming that at least basic python 3 support is working. Feel free to open new, specific bug issues regarding python 3 compatibility if any are found.

@arrfab Thank you for the comment by the way. Without comments from other users we know very little about how other people are using this project.
